# Generated by Django 5.2.5 on 2025-08-25 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_size_alter_category_options_clothingitem_itemimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothingitem',
            name='sizes',
        ),
        migrations.RemoveField(
            model_name='itemimage',
            name='product',
        ),
        migrations.DeleteModel(
            name='ClothingItemSize',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.DeleteModel(
            name='ItemImage',
        ),
    ]
