# Generated by Django 5.2.5 on 2025-08-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_clothingitem_sizes_remove_itemimage_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
