# Generated by Django 5.2.5 on 2025-08-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_clothingitem_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
